#!/bin/bash

rm -rf /etc/yum.repos.d
git clone -b ovirt-beta-engine https://github.com/ogofen/repos-3.5.git /etc/yum.repos.d
git clone https://github.com/ogofen/vim-master.git ./.vim
cp ./init_server/.vimrc ./
cp ./init_server/.zshrc-en ./
mv .zshrc-en .zshrc
cp ./init_server/log.en.vim ./
mv log.en.vim log.vim
yum install xauth -y
yum install ack -y
wget -O .monitor https://www.dropbox.com/s/ckb0w3tysuobc2y/.monitor
chmod +x .monitor
yum install vim-X11 -y
yum install bpython -y
yum install vim -y
yum install gcc -y
yum install ncurse* -y
git clone https://github.com/robbyrussell/oh-my-zsh.git
wget -O zsh-5.0.2.tar.bz2 https://www.dropbox.com/s/i4zuouv46km8p9o/zsh-5.0.2.tar.bz2 && tar xvjf zsh-5.0.2.tar.bz2 && cd zsh-5.0.2
chmod +x configure
./configure
make
make install
echo "/usr/local/bin/zsh" | sudo tee -a /etc/shells
yum install ovirt-release -y
chsh -s /usr/local/bin/zsh
yum install ovirt-engine -y
yum upgrade -y
reboot
