#!/bin/bash

wget -O .zshrc https://www.dropbox.com/s/39l41bsyc3toang/zshrc
yum install xauth -y
yum install ack -y
wget -O .vimrc https://www.dropbox.com/s/bzphm6kwdeuub26/.vimrc
wget -O .monitor https://www.dropbox.com/s/gj3t518zbcjk3al/.monitor
wget -O log.vim https://www.dropbox.com/s/dqwspbgs69k6ta4/log.vim
chmod +x .monitor
yum install vim-X11 -y
yum install bpython
yum install vim -y
yum install gcc -y
yum install ncurse* -y
git clone https://github.com/robbyrussell/oh-my-zsh.git
wget http://sourceforge.net/projects/zsh/files/zsh/5.0.2/zsh-5.0.2.tar.bz2/download && tar xvjf zsh-5.0.2.tar.bz2 && cd zsh-5.0.2
chmod +x configure
./configure
make
make install
echo "/usr/local/bin/zsh" | sudo tee -a /etc/shells
chsh -s /usr/local/bin/zsh

