#!/bin/bash

yum install xauth -y
yum install ack -y
yum install vim-X11 -y
yum install bpython -y
yum install vim -y
yum install gcc -y
yum install ncurse* -y
yum install ctags -y
git clone https://github.com/ogofen/vim ./.vim
cp init/.vimrc ./
git clone https://github.com/robbyrussell/oh-my-zsh.git
yum install zsh -y
echo "/bin/zsh" | sudo tee -a /etc/shells
chsh -s /bin/zsh
